#!/bin/bash

echo "Install Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Install software listed in the Brewfile"
brew bundle --file Brewfile
